# This is a basic workflow to help you get started with Actions

name: ScmPub Test CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: chunyescmpubtest  # set this to your application's name
  CONTAINER_REGISTRY: chunyescr.azurecr.io  # set secret with Container Registry URL, example : xyz.azurecr.io 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: mcr.microsoft.com/dotnet/sdk:5.0-nanoserver-1809

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use docker login to log into ACR
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY_NAME }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Close Hyper-V container parking page image and re-publish it to private repository
        run: |
          docker pull mcr.microsoft.com/azure-app-service/windows/parkingpage:latest
          docker tag mcr.microsoft.com/azure-app-service/windows/parkingpage:latest ${{ env.CONTAINER_REGISTRY }}/containerwebapp/scmpubtest:latest
          docker push ${{ env.CONTAINER_REGISTRY }}/containerwebapp/scmpubtest:latest
          
      # Login with Azure SPN
      - name: Azure Service Principal Authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
     # Deploy Container to Azure App Service
      - name: Deploy Container to Azure App Service
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: ${{ secrets.APP_NAME }}
          images: ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
